Enhancement/#183
pluggedcomputing/pixel pull request #184
Opened 2022-02-21 20:35 UTC by sabrina-goncalves-de-almeida

# Pull Request

### Tipo
* [X]  ~feature
* [ ]  ~bugfix 
* [ ]  ~release
* [ ]  ~hotfix
* [ ]  ~GMUD

### Changelog
> SplashScreen
> Menu principal
> Página Sobre

Closes #183

2022-02-21 20:52 UTC, barbosamaatheus requested changes

2022-02-21 20:52 UTC, barbosamaatheus commented on src/styles/colors.js
> +  colorPrimaryPixel:'#A6F3D6',
Não usar o nome pixel nas cores.

2022-02-21 20:52 UTC, barbosamaatheus commented on src/styles/colors.js
> +  colorTextSecondaryPixel:'#FFFFFF',
Não precisa criar novas cores, vc pode substituir as já existentes para alterar todo o tema do app

2022-02-21 20:52 UTC, barbosamaatheus commented on src/styles/colors.js
> +  colorPrimaryPixelDark: '#07377A',
Essa cor é a cor primária do app? Você precisa de duas cores primárias? Nessa não seria uma cor secundária?

2022-02-21 20:52 UTC, barbosamaatheus commented on src/screens/Main/index.js
> +import logo from '../../assets/images/pixel_cape.png';
O que significa "cape"?

2022-02-21 20:52 UTC, barbosamaatheus commented on src/screens/Main/index.js
> +import logo from '../../assets/images/pixel_cape.png';
Você deve utilizar imagens nos tamanhos @1x, @2x e @3x.

2022-02-21 20:52 UTC, barbosamaatheus commented on src/screens/Main/index.js
> +          REPRESENTAÇÃO DE IMAGENS
Esse texto é em caixa alta?

2022-02-23 01:43 UTC, sabrina-goncalves-de-almeida commented on src/screens/Main/index.js
> +          REPRESENTAÇÃO DE IMAGENS
Sim. Como no figma, mas ainda não alterei a fonte.

2022-02-23 01:45 UTC, sabrina-goncalves-de-almeida commented on src/screens/Main/index.js
> +import logo from '../../assets/images/pixel_cape.png';
Alterarei o nome da imagem para ter um contexto mais claro.

2022-02-23 01:48 UTC, sabrina-goncalves-de-almeida commented on src/styles/colors.js
> +  colorPrimaryPixel:'#A6F3D6',
Ok, entendido!

2022-03-01 20:45 UTC, barbosamaatheus requested changes
Você alterou o ícone do app, acredito que talvez seja necessário atualizar o Android Manifest, por favor verifique.

2022-03-01 20:45 UTC, barbosamaatheus commented on android/app/src/main/res/drawable/background_splash.xml
> +    android:height="160dp"
O ícone não é quadrado? Porque usar tamanhos diferente em width e height?

2022-03-01 20:45 UTC, barbosamaatheus commented on src/screens/Main/index.js
> +          REPRESENTAÇÃO DE IMAGENS
No figama esse nome não é maisuculo. 
```suggestion
         Representação de Imagens
```
![Frame 231](https://user-images.githubusercontent.com/18462250/156243589-7bf9c7f3-ebb2-4c46-a0f3-6e40e764f2c6.png)

2022-03-01 20:45 UTC, barbosamaatheus commented on src/screens/Main/index.js
> -        <CustomButton
Acredito que a tela de sobre vai continuar até que a funcionalidade dos perfis seja implementada. Logo, esse botão não deve ser removido.

@ayladebora por favor confirmar.

2022-03-01 20:45 UTC, barbosamaatheus commented on src/styles/colors.js
>    colorPrimaryLight: '#757de8',
Remover, não acho que essa cor faça parte do tema do novo app. Se fizer, por favor responda esse comentário com o local onde a usamos. 
```suggestion
  
```

2022-03-01 20:45 UTC, barbosamaatheus commented on src/styles/colors.js
>    colorSecondary: '#f2f4ff',
Não estamos usando essa `colorSecondary`. Substituir pelo valor da `colorPrimaryDark` e remover `colorPrimaryDark`.

Remover também as cores;  `colorSecondaryLight: '#ffffff',` e   `colorSecondaryDark: '#bfc1cc',`

Não é legal usar cores com nomes light e dark, pois não estamos usando dois temas e sim apenas um.

```suggestion
  colorSecondary: '#07377A',
```

2022-03-01 20:45 UTC, barbosamaatheus commented on src/styles/colors.js
>    colorSecondaryLight: '#ffffff',
```suggestion

```

2022-03-01 20:45 UTC, barbosamaatheus commented on src/styles/colors.js
>    colorSecondaryDark: '#bfc1cc',
```suggestion

```

2022-03-01 20:45 UTC, barbosamaatheus commented on src/styles/colors.js
>    colorAccent: '#46d3f2',
Podemos usar branco aqui e usar o colorAccent como background nas telas.

Se preferir pode utilizar `colorAcdent: '#757de8' e colorSecondary: '#FFFFFF'`
```suggestion
  colorAccent: '#FFFFFF',
```

2022-03-01 20:45 UTC, barbosamaatheus commented on src/styles/colors.js
>    colorTextPrimary: '#212121',
Observando o figma podemos observar que os textos só podem ser de duas cores. Azul ou branco. Sendo a maioria do texto do app escrito em azul. Logo a cor de texto primeira deve ser azul e a cor de texto secundaria deve ser branco. 
```suggestion
  colorTextPrimary: '#07377A',
```

2022-03-01 20:45 UTC, barbosamaatheus commented on src/styles/metrics.js
> +  borderRadius:7,
Já temos tres tamanhos para border radius: _smallRadius_, _baseRadius_ e _tripleBaseRadius_. O app deve se adaptar e utilizar esses valores para manter o padrão, sem a necessidade de criar-se outro. Se precisar alterar, deve altrar os padrões já existente e seguir usando eles dirante o app.

```suggestion

```

2022-03-01 20:45 UTC, barbosamaatheus commented on android/app/src/main/res/drawable/.comments/splashscreen.jpg.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Porque você precisa desse arquivo? Onde você o usa e, porque?

2022-03-01 20:47 UTC, barbosamaatheus commented
Por favor, edite a issue de referência desse PR para conter a informação da alteração de icone

2022-03-07 19:41 UTC, barbosamaatheus commented on src/screens/ScreenAbout/index.js
> +// import site from '../../assets/images/site.png';
pode remover esse comentarios

2022-03-07 19:43 UTC, barbosamaatheus reviewed
Por favor, responda os meus comentários em que faço perguntas para que eu consiga entender um pouco melhor e aceitar o PR

2022-03-15 10:19 UTC, Lilian-Goncalves-de-Almeida commented on src/screens/Main/index.js
> +          REPRESENTAÇÃO DE IMAGENS
Realmente, não tinha notado, obrigada, já alterei!

2022-03-15 10:27 UTC, sabrina-goncalves-de-almeida commented on src/screens/Main/index.js
> +          REPRESENTAÇÃO DE IMAGENS
Realmente, eu não havia notado, já alterei, obrigada.

2022-03-15 10:28 UTC, sabrina-goncalves-de-almeida commented on android/app/src/main/res/drawable/background_splash.xml
> +    android:height="160dp"
Estou verificando. Retorno quando encontrar mais sobre. Obrigada pela ajuda!

2022-03-15 10:30 UTC, sabrina-goncalves-de-almeida commented on src/styles/colors.js
>    colorPrimaryLight: '#757de8',
Não faz, estava mantendo para poder modificar por outra cor, mas provavelmente não venha a precisa, são poucas cores no novo design.

2022-03-15 10:31 UTC, sabrina-goncalves-de-almeida commented on src/styles/colors.js
>    colorAccent: '#46d3f2',
Já alterei, obrigada.

2022-03-15 10:33 UTC, sabrina-goncalves-de-almeida commented on src/screens/ScreenAbout/index.js
> +// import site from '../../assets/images/site.png';
Ok, vou remover!

2022-03-15 10:37 UTC, sabrina-goncalves-de-almeida commented on src/screens/Main/index.js
> -        <CustomButton
Nós vamos alterar para uma barra de navegação na parte inferior da tela, mas ainda não implementei essa parte, por isso vou colocar o botão novamente, pelo menos até criar a barra. Obrigada.

2022-03-15 10:38 UTC, sabrina-goncalves-de-almeida commented on src/screens/Main/index.js
> +import logo from '../../assets/images/pixel_cape.png';
Já comecei a utilizar. Obrigada.

2022-03-15 10:42 UTC, sabrina-goncalves-de-almeida commented on src/styles/colors.js
>    colorTextPrimary: '#212121',
Ok, já está alterado.

2022-03-15 10:51 UTC, sabrina-goncalves-de-almeida commented on android/app/src/main/res/drawable/.comments/splashscreen.jpg.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Já estava no projeto quando eu comecei a alterar, estou pesquisando sobre, ainda não encontrei muita coisa(só em sites como o stackoverflow), mas pelo que já pesquisei, é um arquivo para definir a língua usada nos texto, estou levada a acreditar, pois UTF-8 é usado em HTML para dizer que a fonte deve mostrar letras do português sem ficar mudando as letras com acentos por outras ou aparecer uma tarja preta no lugar de letras que não existem no inglês. Vou pesquisar mais e te respondo novamente.

2022-03-15 10:53 UTC, sabrina-goncalves-de-almeida commented on src/styles/metrics.js
> +  borderRadius:7,
Vou dar uma olhada nos "radius" de botões e outras partes do projeto, as mais usadas vou colocar nos já existentes, obrigada pelo toque!

2022-03-15 20:25 UTC, barbosamaatheus commented on android/app/src/main/res/drawable/.comments/splashscreen.jpg.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Isso foi um arquivo gerado automaticamente então? no caso, não foi você quem adicionou?

2022-03-15 21:16 UTC, merged