Feature/#190
pluggedcomputing/pixel pull request #192
Opened 2022-04-13 15:13 UTC by sabrina-goncalves-de-almeida

# Pull Request

### Tipo
* [ ]  ~feature
* [ ]  ~bugfix 
* [ ]  ~release
* [ ]  ~hotfix
* [ ]  ~GMUD

### Changelog
> Descrevas suas alterações em formato de lista não ordenada.

Closes <issueId>

2022-04-15 23:25 UTC, barbosamaatheus requested changes

2022-04-15 23:25 UTC, barbosamaatheus commented on src/styles/metrics.js
> +  doubleBasePadding:16,
```suggestion
  biggerPadding:16,
```

2022-04-15 23:25 UTC, barbosamaatheus commented on src/styles/colors.js
> +  colorBlank: '#E5E5E5',
Porque vc precisa dessa cor? onde está sendo usada?

2022-04-15 23:35 UTC, barbosamaatheus requested changes

2022-04-15 23:35 UTC, barbosamaatheus commented on src/screens/HelpScreen/index.js
> +      <ScrollView>
Adicionar `showsVerticalScrollIndicator={false}`

2022-04-22 19:19 UTC, barbosamaatheus commented
@sabrina-goncalves-de-almeida você já fez as alterações solicitadas nesse PR? Precisamos que resolva para podermos fazer o merge o mais rápido possível.

2022-04-22 19:40 UTC, sabrina-goncalves-de-almeida commented on src/styles/metrics.js
> +  doubleBasePadding:16,
Já modifiquei.

2022-04-22 19:40 UTC, sabrina-goncalves-de-almeida commented on src/styles/colors.js
> +  colorBlank: '#E5E5E5',
Estava usando a cor para testar algumas alterações que estava fazendo e esqueci de retirar, obrigada pelo aviso.

2022-04-22 19:41 UTC, sabrina-goncalves-de-almeida commented on src/screens/HelpScreen/index.js
> +      <ScrollView>
Adicionado, obrigada pela ajuda.

2022-04-23 13:39 UTC, barbosamaatheus approved these changes

2022-04-23 13:40 UTC, merged